# Generated by Django 2.0.3 on 2018-03-13 08:41

from django.db import migrations


class Migration(migrations.Migration):
    
    atomic = False
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
    ]
