# Generated by Django 2.0.3 on 2018-03-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='title',
            new_name='day_number',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='publications',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='publications',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='user',
            new_name='plan',
        ),
    ]
