# Generated by Django 2.0.3 on 2018-03-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0007_auto_20180314_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='exercise',
            field=models.ManyToManyField(null=True, to='mygym.Exercise'),
        ),
    ]
